### ISSUE TITLE
R 데이터 패키지 개발 문의

### ISSUE THREAD

**Issue by mrchypark** [opengirok/congress_asset_disclosure#1]
안녕하세요, 항상 투명사회를 위해 노력해주셔서 대단히 감사합니다.

다름이 아니라 제작해주신 본 데이터셋을 분석 언어인 R의 데이터 패키지를 제작할 수 있을지 문의드리려고 합니다.
라이선스에 의하면  CCL로만 선언하시면서 주신 단서가

```단 영리적 이용과 2차적 저작물의 작성은 허용되지 않습니다.```

입니다. 

R 데이터 패키지는 아마도 현재의 구글 시트 데이터를 불러오는 함수를 제공하게 될텐데요.
데이터를 포함하는 형태와 크게 다를바 없어서 아마 2차 저작물로 보실지 싶어 문의를 남기게 되었습니다.

혹시 가능하다면, 제작 후 본 조직에 기증하는 것도 고려하고 있습니다.

그럼 답변 기다리겠습니다.

다시 한 번 정보 공개에 대한 노력과 기여에 대해 감사드립니다.

**Comment by avecjoeun** [comment]
안녕하세요 찬엽님! 좋은 제안 해주셔서 너무 감사하고 환영합니다! 
패키지 제작 후 기증해 주시면 같이 배포와 홍보 진행하도록 하겠습니다:)  

R 데이터패키지 만들기 쉬운 형태로 만드실 때 데이터를 손 볼 것들이 있을것 같은데 언제든지 얘기해 주시구요,
데이터셋 함께 만드신 저희 권혜진 대표님도 인사 전한다고 하셨습니다^-^

앞으로 함께 할 수 있는 것들 종종 도모해보아요! 
감사합니다.

**Comment by mrchypark** [comment]
우선 허락해주셔서 감사합니다. :)

https://github.com/r-krdb/krcad

우선 여기 작업하고 공유드리겠습니다.

데이터는 아시겠지만, 모든 년도 일관된 구조가 가장 중요하지 싶습니다. :)

특별히 작업이 필요하지는 않을 거라 예상하고 있습니다. 혹시 작업이 필요하다면 문의드리겠습니다.
